name: Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
    branches: ["master"]

jobs:
  build-dll:
    name: Build and publish tagged release
    if: startsWith( github.ref, 'refs/tags/v')
    runs-on: windows-2019
    timeout-minutes: 10
    steps:
      - name: Download Tools
        run: |
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
          Invoke-WebRequest -Uri https://github.com/stedolan/jq/releases/download/jq-1.6/jq-win64.exe -OutFile jq.exe
          Invoke-WebRequest -Verbose -Uri https://github.com/moloch--/minisign/releases/download/v0.2.1/minisign.exe -OutFile minisign.exe
          ls

      - name: checkout code
        uses: actions/checkout@v3

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - name: build_x64
        run: "msbuild -p:Configuration=Release -p:Platform=x64 SliverKeylogger.sln"

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x86

      - name: build_x86
        run: "msbuild -p:Configuration=Release -p:Platform=x86 SliverKeylogger.sln"

      - name: make package
        run: |
          mkdir raw-keylogger
          copy bin\\SliverKeylogger.x86.dll raw-keylogger\\SliverKeylogger.x86.dll
          copy bin\\SliverKeylogger.x64.dll raw-keylogger\\SliverKeylogger.x64.dll
          copy extension.json raw-keylogger\\extension.json
          $Version = git.exe describe --tags --abbrev=0
          Get-Content -Path extension.json | jq.exe --arg ver "$Version" '.version |= $ver' > .\raw-keylogger\extension.json
          cd raw-keylogger
          tar -czvf ..\raw-keylogger.tar.gz .

      - name: sign package
        run: |
          Write-Output "${{ secrets.MINISIGN_PRIVATE_KEY }}" > minisign.key
          $Content1 = Get-Content -Path ./raw-keylogger/extension.json
          $Bytes = [System.Text.Encoding]::UTF8.GetBytes($Content1)
          $Encoded = [System.Convert]::ToBase64String($Bytes)
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
          Invoke-WebRequest -Verbose -Uri https://github.com/moloch--/minisign/releases/download/v0.2.1/minisign.exe -OutFile minisign.exe
          ls
          .\minisign.exe -s minisign.key -S -m raw-keylogger.tar.gz -t "$Encoded" -x raw-keylogger.minisig

      - name: "Publish Release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            raw-keylogger.minisig
            raw-keylogger.tar.gz
